### ISSUE TITLE
Missing units or references 

### ISSUE THREAD

**Issue by MyrionPhoenixmoon** [tschoppi/starsystem-gen#26]
Some values currently are unit-less or, if they are relative, missing their references. This must be fixed.

**Comment by MyrionPhoenixmoon** [comment]
Total Tidal Effect needs an explanation, as does Luminosity.
Blackbody Temp is not obvious, either and Mass, Diameter, Density all need a reference point.
Atm. Pressure and Mass need units or references.

**Comment by tschoppi** [comment]
I consulted the rule book for these numbers, my findings are presented below:

- Luminosity is given in solar luminosity, 1.0 corresponds to the energy output of the sun.
- The total tidal effect is an intermediate dimensionless value used for computations of orbital periods and such. Not really necessary to know for the end user.
- Blackbody temperature is the temperature of the body if it were a black body, i.e. an ideal absorber and emitter of heat. Given in K, it is also not really relevant in the end, as it is used in intermediary calculations for surface temperature and such.
- Stellar radii are given in AU.
- Atm. Pressure is given in atmospheres (1 atm = 1013.25 hPa).
- The unit for atmospheric mass is not clearly defined in the rule book. It seems reasonable to interpret it as a relative number to earth atmospheric mass, as it is in the range of 0.5 to 1.5.
- World densities are relative to earth densities. 1.0 is exactly as our earth, lower has more ice, higher has more metal.
- Mass and Diameter are also relative to earth.

**Comment by MyrionPhoenixmoon** [comment]
For stellar radii I converted them to a relative value based on the sun.
