### ISSUE TITLE
Deal with <> in names in a centralized fashion

### ISSUE THREAD

**Issue by MyrionPhoenixmoon** [tschoppi/starsystem-gen#34]
Currently, the names of objects follow the "\<Star_Letter-Index\>" convention, and the < and > characters have to be stripped out in many different places.

This should be changed, either by introducing a helper function to encapsulate the calls to strip the characters or by removing them from the name by default and only adding them when necessary.

**Comment by tschoppi** [comment]
I think adding them when necessary is the better solution.

**Comment by MyrionPhoenixmoon** [comment]
I strongly agree. I think that we'll soon have to do some bigger refactoring, in order to be ready for any new feature yet to come, anyway, and this should be part of it.

**Comment by tschoppi** [comment]
Maybe provide two methods for returning the name, one with the angular brackets and one without. That might make the refactoring easier.

**Comment by MyrionPhoenixmoon** [comment]
So we rename the current version to sth like "get_name_for_latex"?
hmm, that could work!

**Comment by tschoppi** [comment]
I'd say `get_name_angled` which is a wrapper for `get_name` and just sticks the angles left and right.

**Comment by MyrionPhoenixmoon** [comment]
Yeah, sounds good, go right ahead.
