### ISSUE TITLE
Fix stellar orbit graphic

### ISSUE THREAD

**Issue by MyrionPhoenixmoon** [tschoppi/starsystem-gen#36]
It currently only works in Chrome, since the Ellipse function is only supported in Chrome. 

Either use a workaround with Canvas, or migrate the whole thing to SVG.

**Comment by MyrionPhoenixmoon** [comment]
Correction: The Ellipse function is also supported in Edge. However, in Edge Array contents aren't named 0, 1, 2, ... but ms_idXXXX, where I don't even see a pattern to the IDs, breaking the ```for row in rows``` loop.

**Comment by MyrionPhoenixmoon** [comment]
We will need to introduce a bigger library to work with canvas, or more likely, migrate to using SVG.

**Comment by MyrionPhoenixmoon** [comment]
I changed the way I looped through the array of rows, enabling Edge compatibility.

Currently the graphic works on Chrome (Desktop & Mobile), Edge, Safari (Desktop), Opera and Yandex. Whatever Yandex is ;)

Firefox seems to be in the process of reviewing a patch which implements the Ellipse() functionality, so I think we should probably just wait.

**Comment by tschoppi** [comment]
I can confirm that the Ellipse() is drawn in Firefox 49. Thus the compatibility list has grown to:

- Chrome
- Edge
- Firefox
- Safari
- Opera
- Yandex (wherever that comes from)

All major browsers comprise this list, thus the issue of browser compatibility has been resolved.
