### ISSUE TITLE
Fix module imports

### ISSUE THREAD

**Issue by MyrionPhoenixmoon** [tschoppi/starsystem-gen#38]
For some reason, when I tried updating to the newest version of the starsystem-gen on the server, I needed to add to the PYTHONPATH.

We have other, less-than-ideal situations with the module imports. We need to fix these.

**Comment by tschoppi** [comment]
Define the other less-than-ideal situations?

**Comment by MyrionPhoenixmoon** [comment]
I misremembered. Originally there was an issue with the modules which required path manipulation in server.py.

**Comment by tschoppi** [comment]
I do not understand what issues were fixed concerning the `server.py` file, as when I now want to run the server, I get an error:
```
Traceback (most recent call last):                                                      
  File "server.py", line 5, in <module>                                                 
    from gurpsspace import starsystem as starsys                                        
ImportError: No module named 'gurpsspace'
```

I assume I need to add the directory to PYTHONPATH now to fix this? I see this was changed in 0ff23dd5a591ef1534c7b1930355622c51262ed6.

**Comment by MyrionPhoenixmoon** [comment]
Yes, it seems that way. Strangely, this was already the case on my systems...

But this needs to work better in all conditions.

**Comment by MyrionPhoenixmoon** [comment]
OKay, the reason why all these path shenanigans are necessary is that the "main" script (in this case server.py) should be outside of a package! Guido van Rossum sees calling scripts inside a package as an antipattern and thus Python doesn't nicely accomodate this.

I now moved server.py out into the root directory and refactored all relevant paths. Now the imports should work, please confirm.

**Comment by tschoppi** [comment]
I can confirm, it now works without a `$PYTHONPATH` variable.

**Comment by MyrionPhoenixmoon** [comment]
Great!
