### ISSUE TITLE
Set star age properly

### ISSUE THREAD

**Issue by tschoppi** [tschoppi/starsystem-gen#43]
There is a note in the code that says that more recalculations have to be done when the star age is reset to a different value. It is currently not called from anywhere else in the code base. The star age is set directly when the star instance is initialized, as it is used as a parameter for the `__init__` method.

The problem is that many variables afterwards depend on the age of the star. Why this method was implemented is not clear in the first place.

Should the setter be deleted?

**Comment by MyrionPhoenixmoon** [comment]
I would remove it for now. 

We are still at a version <1.0, where I wouldn't worry too much about "breaking" the API. In case we need the setter at some point for serialization (say, to JSON to do something in the frontend) we can easily reintroduce it.
