### ISSUE TITLE
Change from buttons to links in webGUI

### ISSUE THREAD

**Issue by tschoppi** [tschoppi/starsystem-gen#53]
# Issue
Currently, there are buttons in the data tables that indicate clickable content, which then take you to a new page. While on this new page, the browser navigation buttons (backwards and forwards) do not work as intuitively expected.

## Examples
Overview page
![screenshot from 2016-10-07 13-36-15](https://cloud.githubusercontent.com/assets/8062819/19188612/2af28b90-8c93-11e6-829d-d3cc6fe5785e.png)
Starsystem page
![screenshot from 2016-10-07 13-36-47](https://cloud.githubusercontent.com/assets/8062819/19188618/35393d24-8c93-11e6-8b98-7b91d27db19f.png)

# Resolution
I suggest moving from these buttons, which open the content in a new tab, to links that open the content in the same tab. This also allows for a more uniform look within the tables, as rows with buttons are slightly greater in height than those without (see example on starsystem page above).

Comments are appreciated.

**Comment by MyrionPhoenixmoon** [comment]
The original idea was to open them in a pop-up or a modal window overlay. Pop-ups are so utterly disdained these days, however, that it would take considerable effort to create one.

The overlay also produces other issues, so I created a branch and fixed this issue. See PR #56
